Modifies tunning logic of porta
Now that we've found that cpu-quota/cpu-period affects the way in which
memguard behaves, we need to take this into account in the tuning logic
of porta. The changes in docker/porta reflect this. Basically, we tune
CPU first, then apply those CPU parameters to the benchmarks that are
used to tune memory.

This commit also creates a 'tune-targets' playbook that is in charge of
this task. We then create a 'base-vs-limited-target' playbook that
executes benchmarks on a target with/without limits.

diff --git a/porta b/porta
--- a/porta
+++ b/porta
@@ -19,6 +19,10 @@ case $1 in
     ;;
   "tune")
     echo "" > parameters.json
+    if [ ! -f base.json ] ; then
+      echo "Cannot find base.json file"
+      exit 1
+    fi
     docker run \
       --rm \
       --privileged \
@@ -32,6 +36,10 @@ case $1 in
          ivotron/porta --parallelism 1 --test-limit 20 --technique MonotonicSearch --bail-threshold 1 --action $@
     ;;
   "run")
+    if [ ! -f parameters.json ] ; then
+      echo "Cannot find parameters.json file"
+      exit 1
+    fi
     docker run \
       --rm \
       --privileged \
